<?php
// $Id$

/**
* Implementation of hook_menu()
*/
function multiple_users_autocomplete_menu(){
	  $items = array();

	$items['user/autocomplete/multiple'] = array(
		'title' => 'Multiple users autocomplete',
    'page callback' => 'multiple_users_autocomplete_multiple',
   	'access callback' => 'user_access',
   	'access arguments' => array('access user profiles'),
   	'type' => MENU_CALLBACK,
	); 
	
	return $items;
}


/** 
 * Autocomplete for a form field of comma-separated usernames 
 */  

function multiple_users_autocomplete_multiple($string = '') {
  
  $array = drupal_explode_tags($string);

  $last_string = trim(array_pop($array));
  $matches = array();
  
  if ($last_string != '') {
    $result = db_select('users')->fields('users', array('name'))->condition('name', db_like($last_string) . '%', 'LIKE')->range(0, 10)->execute();
    $prefix = count($array) ? implode(', ', $array) .', ' : '';
    while ($user = $result->fetchObject()) {
      $n = $user->name;
      $matches[$prefix . $n] = check_plain($user->name);
    }
  }

  drupal_json_output($matches);
}